#!/usr/bin/env bash
# Regenerate derived files. Never hand-edit the outputs.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1. AGENTS.md is a byte-identical twin of CLAUDE.md
cp CLAUDE.md AGENTS.md

# 2. decisions/_index.md from ADR frontmatter
{
  echo "# Decisions — index (generated by _scripts/gen-indexes.sh; do not edit)"
  echo
  echo "| ADR | Status | Date | Title |"
  echo "|---|---|---|---|"
  # NNNN-kebab-title.md only: the trailing [a-z] stops date-named files
  # (e.g. 2026-08-17-foundation-ultra-review.md) being indexed as ADR "2026".
  for f in decisions/[0-9][0-9][0-9][0-9]-[a-z]*.md; do
    id=$(basename "$f" .md | cut -d- -f1)
    status=$(sed -n 's/^status: *//p' "$f" | head -1)
    date=$(sed -n 's/^date: *//p' "$f" | head -1)
    title=$(grep -m1 '^# ' "$f" | sed 's/^# [0-9]* — //; s/^# //')
    echo "| [$id]($(basename "$f")) | $status | $date | $title |"
  done
} > decisions/_index.md

# 3. map/objects/_index.md from card frontmatter (only if the shelf exists)
if [ -d map/objects ]; then
  {
    echo "# Objects — index (generated; do not edit)"
    echo
    echo "| Card | Cluster | Universe | Status |"
    echo "|---|---|---|---|"
    for f in map/objects/*.md; do
      [ "$(basename "$f")" = "_index.md" ] && continue
      echo "| [$(basename "$f" .md)]($(basename "$f")) | $(sed -n 's/^cluster: *//p' "$f" | head -1) | $(sed -n 's/^universe: *//p' "$f" | head -1) | $(sed -n 's/^status: *//p' "$f" | head -1) |"
    done
  } > map/objects/_index.md
fi
echo "indexes regenerated"
